name: Output to populate issues
on: issues
jobs:
    output:
        runs-on: ubuntu-latest
        steps:
            - name: capturing the output events
              run: echo "${{ toJson(github.event) }}"